images:
  ubuntu_custom_x64:
    platform: "linux"
    arch: "x64"
    owner: "135269210855"
    name: "runs-on-v2.2-ubuntu24-full-x64-*"
    preinstall: |
      sudo systemctl stop docker.socket
      sudo systemctl stop docker

      # Remove Docker and related packages
      sudo apt-get purge -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      sudo apt-get install -y podman buildah

      sudo apt-get autoremove -y
      sudo apt-get clean
