name: celestial-silverblue
description: A custom image of Fedora Silverblue with personal modifications.

base-image: ghcr.io/secureblue/silverblue-nvidia-hardened
image-version: 40

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
    install:
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-pop-shell
      - pop-gnome-shell-theme
      - wezterm
      - file-roller
      - distrobox
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

